name: Build (ci-windows)

on:
  workflow_dispatch:

jobs:
  build:
    name: Build (2022)
    runs-on: windows-2022
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Build Docker Image
        shell: powershell
        run: docker build -t sil-kit-ci-windows:2022 ./containers/ci-windows

      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry: "ghcr.io"
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: ./containers/ci-windows/
      #     file: ./containers/ci-windows/Dockerfile
      #     push: true
      #     load: true
      #     tags: sil-kit-ci-windows:2022

      # - name: Test the image
      #   run: |
      #     docker run -itd --name emmy_noether sil-kit-test:latest /bin/bash
      #     docker cp ./utils/image_tests.sh emmy_noether:/home/image_tests.sh
      #     docker exec -w /home/  emmy_noether sh image_tests.sh 8
